### ISSUE TITLE
pronto crashes with simple command

### ISSUE THREAD

**Issue by ptarjan** [mmozuras/pronto#131] opened 2016-03-07 18:16 UTC
I just installed `pronto` to try it, and when running I get:

```
$ pronto run
/Users/pt/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/pronto-0.5.3/lib/pronto/git/patches.rb:11:in `each_patch': illegal byte sequence (Rugged::RegexError)
        from /Users/pt/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/pronto-0.5.3/lib/pronto/git/patches.rb:11:in `map'
        from /Users/pt/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/pronto-0.5.3/lib/pronto/git/patches.rb:11:in `initialize'
        from /Users/pt/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/pronto-0.5.3/lib/pronto/git/repository.rb:17:in `new'
        from /Users/pt/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/pronto-0.5.3/lib/pronto/git/repository.rb:17:in `diff'
        from /Users/pt/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/pronto-0.5.3/lib/pronto.rb:37:in `run'
        from /Users/pt/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/pronto-0.5.3/lib/pronto/cli.rb:52:in `run'
        from /Users/pt/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /Users/pt/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /Users/pt/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /Users/pt/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /Users/pt/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/pronto-0.5.3/bin/pronto:6:in `<top (required)>'
        from /Users/pt/.rbenv/versions/2.1/bin/pronto:23:in `load'
        from /Users/pt/.rbenv/versions/2.1/bin/pronto:23:in `<main>'
```

And the same thing when trying the second command

```
$ pronto run --commit=$(git log --pretty=format:%H | tail -1)
/Users/pt/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/pronto-0.5.3/lib/pronto/git/patches.rb:11:in `each_patch': illegal byte sequence (Rugged::RegexError)
        from /Users/pt/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/pronto-0.5.3/lib/pronto/git/patches.rb:11:in `map'
        from /Users/pt/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/pronto-0.5.3/lib/pronto/git/patches.rb:11:in `initialize'
        from /Users/pt/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/pronto-0.5.3/lib/pronto/git/repository.rb:17:in `new'
        from /Users/pt/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/pronto-0.5.3/lib/pronto/git/repository.rb:17:in `diff'
        from /Users/pt/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/pronto-0.5.3/lib/pronto.rb:37:in `run'
        from /Users/pt/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/pronto-0.5.3/lib/pronto/cli.rb:52:in `run'
        from /Users/pt/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /Users/pt/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /Users/pt/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /Users/pt/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /Users/pt/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/pronto-0.5.3/bin/pronto:6:in `<top (required)>'
        from /Users/pt/.rbenv/versions/2.1/bin/pronto:23:in `load'
        from /Users/pt/.rbenv/versions/2.1/bin/pronto:23:in `<main>'
```

These work:

```
$ pronto list
flay
rubocop
```

```
$ pronto version
Pronto version 0.5.3
```

**Comment by mmozuras** [comment] 2016-03-13 20:52
@ptarjan weird. Since it raises a `Rugged` error (a git library used by `pronto`), could you try running it on a different repo and report the results?

**Comment by shalecraig** [comment] 2016-03-15 06:21
I work with and (probably) have a similar machine to @ptarjan, but ran into the same issue.

Running on this repo, it succeeds:
```bash
> git clone git@github.com:mmozuras/pronto.git
> cd pronto
> pronto version
0.6.0
> pronto list
[no output]
> pronto run
[no output, no error code]

# [installs gem install pronto-flay pronto-rubocop]
> pronto list
flay
rubocop
> pronto run
[no output, no error code]
```

What's the next thing I should look at?

**Comment by shalecraig** [comment] 2016-03-15 07:12
I resolved this for myself:
- Ran `git fsck --full --strict` on the repo. Other than dangling commits, it reported no issues.
- Looks like `pronto run` raises somewhere in [this method](https://github.com/libgit2/rugged/blob/7d00d841b689115481b5296e2bd99887cc5f0b75/ext/rugged/rugged_diff.c#L460)
- `Rugged::RegexError` maps to [`GITERR_REGEX`](https://github.com/libgit2/rugged/blob/6883a55b0d415a102fc4606546aa32b4ab43a1e0/ext/rugged/rugged.c#L36)
- Reading a StackOverflow [post](http://unix.stackexchange.com/questions/141420/tr-complains-of-illegal-byte-sequence) about the topic, it suggests setting `export LC_CTYPE=C`.

That works, what.

**Comment by mmozuras** [comment] 2016-04-03 14:13
@shalecraig @ptarjan not sure if that's something that should be handled with `pronto.` But could either of you create a repo on GitHub, which could be used to reproduce the issue?

**Comment by mmozuras** [comment] 2017-03-04 15:52
Closing this issue. It's not something that should be handled by pronto. In case you do encounter it, please try the fix suggested by @shalecraig.

**Closed by mmozuras** 2017-03-04 15:52 UTC
